Workflow update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,47 +1,96 @@
-name: deploy-next (Deploy staging environments to Github Actions)
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
+#
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
+#
+name: Deploy Next.js site to Pages
 
 on:
+  # Runs on pushes targeting the default branch
   push:
-    branches:
-      - master
-  repository_dispatch:
-    types: [deploy-next, deploy-staging]
+    branches: ["master"]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
 
 jobs:
-  next:
+  # Build job
+  build:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: [18.17.1]
     steps:
-      - name: Use Node.js 14.x
-        uses: actions/setup-node@v2
-        with:
-          node-version: "14.x"
-          cache: yarn
-      - name: Install dependencies
-        run: yarn install --immutable --immutable-cache
-      - name: Update to latest release candidate
-        run: yarn update-next
-      - name: Set env vars
-        uses: ./.github/actions/set-dotenv
-      - name: Build project
-        run: yarn build
-      - name: Export project
-        run: yarn export
-      - name: Deploying to Github Pages
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          git config --global user.email ${{ secrets.BOT_EMAIL }}
-          git config --global user.name ${{ secrets.BOT_NAME }}
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v3
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        env:
+          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Export static files
+        run: npm run export
+      - name: List Files
+        run: ls -a
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: out
 
-          git checkout -- package.json
-          git checkout -- yarn.lock
-          git fetch origin gh-pages
-          git checkout -b gh-pages origin/gh-pages
-          git update-ref -d refs/remotes/origin/gh-pages
-          git pull origin gh-pages
-
-          rm -rf next
-          mkdir -p next
-          cp -rf out/* next
-
-          git add -f next
-          git commit -m "chore(deploy): deploy next to GitHub Pages"
-          git push origin gh-pages
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
